#ifndef DATABASELOGIC_GLOBAL_H
#define DATABASELOGIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASELOGIC_LIBRARY)
#  define DATABASELOGICSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASELOGICSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASELOGIC_GLOBAL_H
